/*
 * generated by Xtext 2.21.0
 */
package org.xtext.nusmv.language;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class NuSMVRuntimeModule extends AbstractNuSMVRuntimeModule {
}
