/*
 * generated by Xtext 2.21.0
 */
package org.xtext.nusmv.language.web;

import org.eclipse.xtext.web.server.DefaultWebModule;

/**
 * Manual modifications go to {@link NuSMVWebModule}.
 */
@SuppressWarnings("all")
public abstract class AbstractNuSMVWebModule extends DefaultWebModule {

}
