/**
 * generated by Xtext 2.21.0
 */
package org.xtext.nusmv.language.nuSMV;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Binary Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.nusmv.language.nuSMV.BinaryExpression#getLeft <em>Left</em>}</li>
 *   <li>{@link org.xtext.nusmv.language.nuSMV.BinaryExpression#getOperator <em>Operator</em>}</li>
 *   <li>{@link org.xtext.nusmv.language.nuSMV.BinaryExpression#getRight <em>Right</em>}</li>
 *   <li>{@link org.xtext.nusmv.language.nuSMV.BinaryExpression#getOp <em>Op</em>}</li>
 * </ul>
 *
 * @see org.xtext.nusmv.language.nuSMV.NuSMVPackage#getBinaryExpression()
 * @model
 * @generated
 */
public interface BinaryExpression extends SimpleExpression
{
  /**
   * Returns the value of the '<em><b>Left</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Left</em>' containment reference.
   * @see #setLeft(SimpleExpression)
   * @see org.xtext.nusmv.language.nuSMV.NuSMVPackage#getBinaryExpression_Left()
   * @model containment="true"
   * @generated
   */
  SimpleExpression getLeft();

  /**
   * Sets the value of the '{@link org.xtext.nusmv.language.nuSMV.BinaryExpression#getLeft <em>Left</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Left</em>' containment reference.
   * @see #getLeft()
   * @generated
   */
  void setLeft(SimpleExpression value);

  /**
   * Returns the value of the '<em><b>Operator</b></em>' attribute.
   * The literals are from the enumeration {@link org.xtext.nusmv.language.nuSMV.operators}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Operator</em>' attribute.
   * @see org.xtext.nusmv.language.nuSMV.operators
   * @see #setOperator(operators)
   * @see org.xtext.nusmv.language.nuSMV.NuSMVPackage#getBinaryExpression_Operator()
   * @model
   * @generated
   */
  operators getOperator();

  /**
   * Sets the value of the '{@link org.xtext.nusmv.language.nuSMV.BinaryExpression#getOperator <em>Operator</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Operator</em>' attribute.
   * @see org.xtext.nusmv.language.nuSMV.operators
   * @see #getOperator()
   * @generated
   */
  void setOperator(operators value);

  /**
   * Returns the value of the '<em><b>Right</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Right</em>' containment reference.
   * @see #setRight(SimpleExpression)
   * @see org.xtext.nusmv.language.nuSMV.NuSMVPackage#getBinaryExpression_Right()
   * @model containment="true"
   * @generated
   */
  SimpleExpression getRight();

  /**
   * Sets the value of the '{@link org.xtext.nusmv.language.nuSMV.BinaryExpression#getRight <em>Right</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Right</em>' containment reference.
   * @see #getRight()
   * @generated
   */
  void setRight(SimpleExpression value);

  /**
   * Returns the value of the '<em><b>Op</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Op</em>' attribute.
   * @see #setOp(String)
   * @see org.xtext.nusmv.language.nuSMV.NuSMVPackage#getBinaryExpression_Op()
   * @model
   * @generated
   */
  String getOp();

  /**
   * Sets the value of the '{@link org.xtext.nusmv.language.nuSMV.BinaryExpression#getOp <em>Op</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Op</em>' attribute.
   * @see #getOp()
   * @generated
   */
  void setOp(String value);

} // BinaryExpression
