/**
 * generated by Xtext 2.21.0
 */
package org.xtext.nusmv.language.nuSMV;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Compute Specification</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.nusmv.language.nuSMV.ComputeSpecification#getMinMax <em>Min Max</em>}</li>
 *   <li>{@link org.xtext.nusmv.language.nuSMV.ComputeSpecification#getFirst <em>First</em>}</li>
 *   <li>{@link org.xtext.nusmv.language.nuSMV.ComputeSpecification#getSecond <em>Second</em>}</li>
 *   <li>{@link org.xtext.nusmv.language.nuSMV.ComputeSpecification#isSemicolon <em>Semicolon</em>}</li>
 * </ul>
 *
 * @see org.xtext.nusmv.language.nuSMV.NuSMVPackage#getComputeSpecification()
 * @model
 * @generated
 */
public interface ComputeSpecification extends ModuleElement
{
  /**
   * Returns the value of the '<em><b>Min Max</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Min Max</em>' attribute.
   * @see #setMinMax(String)
   * @see org.xtext.nusmv.language.nuSMV.NuSMVPackage#getComputeSpecification_MinMax()
   * @model
   * @generated
   */
  String getMinMax();

  /**
   * Sets the value of the '{@link org.xtext.nusmv.language.nuSMV.ComputeSpecification#getMinMax <em>Min Max</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Min Max</em>' attribute.
   * @see #getMinMax()
   * @generated
   */
  void setMinMax(String value);

  /**
   * Returns the value of the '<em><b>First</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>First</em>' containment reference.
   * @see #setFirst(RTCTLExpression)
   * @see org.xtext.nusmv.language.nuSMV.NuSMVPackage#getComputeSpecification_First()
   * @model containment="true"
   * @generated
   */
  RTCTLExpression getFirst();

  /**
   * Sets the value of the '{@link org.xtext.nusmv.language.nuSMV.ComputeSpecification#getFirst <em>First</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>First</em>' containment reference.
   * @see #getFirst()
   * @generated
   */
  void setFirst(RTCTLExpression value);

  /**
   * Returns the value of the '<em><b>Second</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Second</em>' containment reference.
   * @see #setSecond(RTCTLExpression)
   * @see org.xtext.nusmv.language.nuSMV.NuSMVPackage#getComputeSpecification_Second()
   * @model containment="true"
   * @generated
   */
  RTCTLExpression getSecond();

  /**
   * Sets the value of the '{@link org.xtext.nusmv.language.nuSMV.ComputeSpecification#getSecond <em>Second</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Second</em>' containment reference.
   * @see #getSecond()
   * @generated
   */
  void setSecond(RTCTLExpression value);

  /**
   * Returns the value of the '<em><b>Semicolon</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Semicolon</em>' attribute.
   * @see #setSemicolon(boolean)
   * @see org.xtext.nusmv.language.nuSMV.NuSMVPackage#getComputeSpecification_Semicolon()
   * @model
   * @generated
   */
  boolean isSemicolon();

  /**
   * Sets the value of the '{@link org.xtext.nusmv.language.nuSMV.ComputeSpecification#isSemicolon <em>Semicolon</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Semicolon</em>' attribute.
   * @see #isSemicolon()
   * @generated
   */
  void setSemicolon(boolean value);

} // ComputeSpecification
