/**
 * generated by Xtext 2.21.0
 */
package org.xtext.nusmv.language.nuSMV;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ctl Specification</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.nusmv.language.nuSMV.CtlSpecification#getSpecKeyWord <em>Spec Key Word</em>}</li>
 *   <li>{@link org.xtext.nusmv.language.nuSMV.CtlSpecification#isNameKeyWord <em>Name Key Word</em>}</li>
 *   <li>{@link org.xtext.nusmv.language.nuSMV.CtlSpecification#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.nusmv.language.nuSMV.CtlSpecification#getCtlExpression <em>Ctl Expression</em>}</li>
 *   <li>{@link org.xtext.nusmv.language.nuSMV.CtlSpecification#isSemicolon <em>Semicolon</em>}</li>
 * </ul>
 *
 * @see org.xtext.nusmv.language.nuSMV.NuSMVPackage#getCtlSpecification()
 * @model
 * @generated
 */
public interface CtlSpecification extends ModuleElement
{
  /**
   * Returns the value of the '<em><b>Spec Key Word</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Spec Key Word</em>' attribute.
   * @see #setSpecKeyWord(String)
   * @see org.xtext.nusmv.language.nuSMV.NuSMVPackage#getCtlSpecification_SpecKeyWord()
   * @model
   * @generated
   */
  String getSpecKeyWord();

  /**
   * Sets the value of the '{@link org.xtext.nusmv.language.nuSMV.CtlSpecification#getSpecKeyWord <em>Spec Key Word</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Spec Key Word</em>' attribute.
   * @see #getSpecKeyWord()
   * @generated
   */
  void setSpecKeyWord(String value);

  /**
   * Returns the value of the '<em><b>Name Key Word</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name Key Word</em>' attribute.
   * @see #setNameKeyWord(boolean)
   * @see org.xtext.nusmv.language.nuSMV.NuSMVPackage#getCtlSpecification_NameKeyWord()
   * @model
   * @generated
   */
  boolean isNameKeyWord();

  /**
   * Sets the value of the '{@link org.xtext.nusmv.language.nuSMV.CtlSpecification#isNameKeyWord <em>Name Key Word</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name Key Word</em>' attribute.
   * @see #isNameKeyWord()
   * @generated
   */
  void setNameKeyWord(boolean value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.nusmv.language.nuSMV.NuSMVPackage#getCtlSpecification_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.nusmv.language.nuSMV.CtlSpecification#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Ctl Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ctl Expression</em>' containment reference.
   * @see #setCtlExpression(CTLExpression)
   * @see org.xtext.nusmv.language.nuSMV.NuSMVPackage#getCtlSpecification_CtlExpression()
   * @model containment="true"
   * @generated
   */
  CTLExpression getCtlExpression();

  /**
   * Sets the value of the '{@link org.xtext.nusmv.language.nuSMV.CtlSpecification#getCtlExpression <em>Ctl Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ctl Expression</em>' containment reference.
   * @see #getCtlExpression()
   * @generated
   */
  void setCtlExpression(CTLExpression value);

  /**
   * Returns the value of the '<em><b>Semicolon</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Semicolon</em>' attribute.
   * @see #setSemicolon(boolean)
   * @see org.xtext.nusmv.language.nuSMV.NuSMVPackage#getCtlSpecification_Semicolon()
   * @model
   * @generated
   */
  boolean isSemicolon();

  /**
   * Sets the value of the '{@link org.xtext.nusmv.language.nuSMV.CtlSpecification#isSemicolon <em>Semicolon</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Semicolon</em>' attribute.
   * @see #isSemicolon()
   * @generated
   */
  void setSemicolon(boolean value);

} // CtlSpecification
