/**
 * generated by Xtext 2.21.0
 */
package org.xtext.nusmv.language.nuSMV;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Enum Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.nusmv.language.nuSMV.EnumType#getVal <em>Val</em>}</li>
 * </ul>
 *
 * @see org.xtext.nusmv.language.nuSMV.NuSMVPackage#getEnumType()
 * @model
 * @generated
 */
public interface EnumType extends SimpleType
{
  /**
   * Returns the value of the '<em><b>Val</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.nusmv.language.nuSMV.Val}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Val</em>' containment reference list.
   * @see org.xtext.nusmv.language.nuSMV.NuSMVPackage#getEnumType_Val()
   * @model containment="true"
   * @generated
   */
  EList<Val> getVal();

} // EnumType
