/**
 * generated by Xtext 2.21.0
 */
package org.xtext.nusmv.language.nuSMV;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Fairness Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.nusmv.language.nuSMV.FairnessExpression#getFairnessExpr <em>Fairness Expr</em>}</li>
 * </ul>
 *
 * @see org.xtext.nusmv.language.nuSMV.NuSMVPackage#getFairnessExpression()
 * @model
 * @generated
 */
public interface FairnessExpression extends FairnessConstraint
{
  /**
   * Returns the value of the '<em><b>Fairness Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Fairness Expr</em>' containment reference.
   * @see #setFairnessExpr(SimpleExpression)
   * @see org.xtext.nusmv.language.nuSMV.NuSMVPackage#getFairnessExpression_FairnessExpr()
   * @model containment="true"
   * @generated
   */
  SimpleExpression getFairnessExpr();

  /**
   * Sets the value of the '{@link org.xtext.nusmv.language.nuSMV.FairnessExpression#getFairnessExpr <em>Fairness Expr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Fairness Expr</em>' containment reference.
   * @see #getFairnessExpr()
   * @generated
   */
  void setFairnessExpr(SimpleExpression value);

} // FairnessExpression
