/**
 * generated by Xtext 2.21.0
 */
package org.xtext.nusmv.language.nuSMV;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Invar Specification</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.nusmv.language.nuSMV.InvarSpecification#getInvarSpec <em>Invar Spec</em>}</li>
 *   <li>{@link org.xtext.nusmv.language.nuSMV.InvarSpecification#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.nusmv.language.nuSMV.InvarSpecification#isSemicolon <em>Semicolon</em>}</li>
 * </ul>
 *
 * @see org.xtext.nusmv.language.nuSMV.NuSMVPackage#getInvarSpecification()
 * @model
 * @generated
 */
public interface InvarSpecification extends ModuleElement
{
  /**
   * Returns the value of the '<em><b>Invar Spec</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Invar Spec</em>' containment reference.
   * @see #setInvarSpec(NextExpression)
   * @see org.xtext.nusmv.language.nuSMV.NuSMVPackage#getInvarSpecification_InvarSpec()
   * @model containment="true"
   * @generated
   */
  NextExpression getInvarSpec();

  /**
   * Sets the value of the '{@link org.xtext.nusmv.language.nuSMV.InvarSpecification#getInvarSpec <em>Invar Spec</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Invar Spec</em>' containment reference.
   * @see #getInvarSpec()
   * @generated
   */
  void setInvarSpec(NextExpression value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.nusmv.language.nuSMV.NuSMVPackage#getInvarSpecification_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.nusmv.language.nuSMV.InvarSpecification#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Semicolon</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Semicolon</em>' attribute.
   * @see #setSemicolon(boolean)
   * @see org.xtext.nusmv.language.nuSMV.NuSMVPackage#getInvarSpecification_Semicolon()
   * @model
   * @generated
   */
  boolean isSemicolon();

  /**
   * Sets the value of the '{@link org.xtext.nusmv.language.nuSMV.InvarSpecification#isSemicolon <em>Semicolon</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Semicolon</em>' attribute.
   * @see #isSemicolon()
   * @generated
   */
  void setSemicolon(boolean value);

} // InvarSpecification
