/**
 * generated by Xtext 2.21.0
 */
package org.xtext.nusmv.language.nuSMV;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Invar Constraint</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.nusmv.language.nuSMV.InvarConstraint#getInvarExpression <em>Invar Expression</em>}</li>
 *   <li>{@link org.xtext.nusmv.language.nuSMV.InvarConstraint#isSemicolon <em>Semicolon</em>}</li>
 * </ul>
 *
 * @see org.xtext.nusmv.language.nuSMV.NuSMVPackage#getInvarConstraint()
 * @model
 * @generated
 */
public interface InvarConstraint extends ModuleElement
{
  /**
   * Returns the value of the '<em><b>Invar Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Invar Expression</em>' containment reference.
   * @see #setInvarExpression(SimpleExpression)
   * @see org.xtext.nusmv.language.nuSMV.NuSMVPackage#getInvarConstraint_InvarExpression()
   * @model containment="true"
   * @generated
   */
  SimpleExpression getInvarExpression();

  /**
   * Sets the value of the '{@link org.xtext.nusmv.language.nuSMV.InvarConstraint#getInvarExpression <em>Invar Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Invar Expression</em>' containment reference.
   * @see #getInvarExpression()
   * @generated
   */
  void setInvarExpression(SimpleExpression value);

  /**
   * Returns the value of the '<em><b>Semicolon</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Semicolon</em>' attribute.
   * @see #setSemicolon(boolean)
   * @see org.xtext.nusmv.language.nuSMV.NuSMVPackage#getInvarConstraint_Semicolon()
   * @model
   * @generated
   */
  boolean isSemicolon();

  /**
   * Sets the value of the '{@link org.xtext.nusmv.language.nuSMV.InvarConstraint#isSemicolon <em>Semicolon</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Semicolon</em>' attribute.
   * @see #isSemicolon()
   * @generated
   */
  void setSemicolon(boolean value);

} // InvarConstraint
