/**
 * generated by Xtext 2.21.0
 */
package org.xtext.nusmv.language.nuSMV;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Justice Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.nusmv.language.nuSMV.JusticeExpression#getJusticeExpr <em>Justice Expr</em>}</li>
 * </ul>
 *
 * @see org.xtext.nusmv.language.nuSMV.NuSMVPackage#getJusticeExpression()
 * @model
 * @generated
 */
public interface JusticeExpression extends FairnessConstraint
{
  /**
   * Returns the value of the '<em><b>Justice Expr</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Justice Expr</em>' containment reference.
   * @see #setJusticeExpr(SimpleExpression)
   * @see org.xtext.nusmv.language.nuSMV.NuSMVPackage#getJusticeExpression_JusticeExpr()
   * @model containment="true"
   * @generated
   */
  SimpleExpression getJusticeExpr();

  /**
   * Sets the value of the '{@link org.xtext.nusmv.language.nuSMV.JusticeExpression#getJusticeExpr <em>Justice Expr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Justice Expr</em>' containment reference.
   * @see #getJusticeExpr()
   * @generated
   */
  void setJusticeExpr(SimpleExpression value);

} // JusticeExpression
