/**
 * generated by Xtext 2.21.0
 */
package org.xtext.nusmv.language.nuSMV;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>LTL Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.nusmv.language.nuSMV.LTLExpression#getSimpleExpression <em>Simple Expression</em>}</li>
 * </ul>
 *
 * @see org.xtext.nusmv.language.nuSMV.NuSMVPackage#getLTLExpression()
 * @model
 * @generated
 */
public interface LTLExpression extends EObject
{
  /**
   * Returns the value of the '<em><b>Simple Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Simple Expression</em>' containment reference.
   * @see #setSimpleExpression(SimpleExpression)
   * @see org.xtext.nusmv.language.nuSMV.NuSMVPackage#getLTLExpression_SimpleExpression()
   * @model containment="true"
   * @generated
   */
  SimpleExpression getSimpleExpression();

  /**
   * Sets the value of the '{@link org.xtext.nusmv.language.nuSMV.LTLExpression#getSimpleExpression <em>Simple Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Simple Expression</em>' containment reference.
   * @see #getSimpleExpression()
   * @generated
   */
  void setSimpleExpression(SimpleExpression value);

} // LTLExpression
