/**
 * generated by Xtext 2.21.0
 */
package org.xtext.nusmv.language.nuSMV;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Ltl Specification</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.nusmv.language.nuSMV.LtlSpecification#isNameId <em>Name Id</em>}</li>
 *   <li>{@link org.xtext.nusmv.language.nuSMV.LtlSpecification#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.nusmv.language.nuSMV.LtlSpecification#getLtlExpression <em>Ltl Expression</em>}</li>
 *   <li>{@link org.xtext.nusmv.language.nuSMV.LtlSpecification#isSemicolon <em>Semicolon</em>}</li>
 * </ul>
 *
 * @see org.xtext.nusmv.language.nuSMV.NuSMVPackage#getLtlSpecification()
 * @model
 * @generated
 */
public interface LtlSpecification extends ModuleElement
{
  /**
   * Returns the value of the '<em><b>Name Id</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name Id</em>' attribute.
   * @see #setNameId(boolean)
   * @see org.xtext.nusmv.language.nuSMV.NuSMVPackage#getLtlSpecification_NameId()
   * @model
   * @generated
   */
  boolean isNameId();

  /**
   * Sets the value of the '{@link org.xtext.nusmv.language.nuSMV.LtlSpecification#isNameId <em>Name Id</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name Id</em>' attribute.
   * @see #isNameId()
   * @generated
   */
  void setNameId(boolean value);

  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.nusmv.language.nuSMV.NuSMVPackage#getLtlSpecification_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.nusmv.language.nuSMV.LtlSpecification#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Ltl Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ltl Expression</em>' containment reference.
   * @see #setLtlExpression(LTLExpression)
   * @see org.xtext.nusmv.language.nuSMV.NuSMVPackage#getLtlSpecification_LtlExpression()
   * @model containment="true"
   * @generated
   */
  LTLExpression getLtlExpression();

  /**
   * Sets the value of the '{@link org.xtext.nusmv.language.nuSMV.LtlSpecification#getLtlExpression <em>Ltl Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ltl Expression</em>' containment reference.
   * @see #getLtlExpression()
   * @generated
   */
  void setLtlExpression(LTLExpression value);

  /**
   * Returns the value of the '<em><b>Semicolon</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Semicolon</em>' attribute.
   * @see #setSemicolon(boolean)
   * @see org.xtext.nusmv.language.nuSMV.NuSMVPackage#getLtlSpecification_Semicolon()
   * @model
   * @generated
   */
  boolean isSemicolon();

  /**
   * Sets the value of the '{@link org.xtext.nusmv.language.nuSMV.LtlSpecification#isSemicolon <em>Semicolon</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Semicolon</em>' attribute.
   * @see #isSemicolon()
   * @generated
   */
  void setSemicolon(boolean value);

} // LtlSpecification
