/**
 * generated by Xtext 2.21.0
 */
package org.xtext.nusmv.language.nuSMV;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Module Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.nusmv.language.nuSMV.ModuleType#getModule <em>Module</em>}</li>
 *   <li>{@link org.xtext.nusmv.language.nuSMV.ModuleType#getParams <em>Params</em>}</li>
 *   <li>{@link org.xtext.nusmv.language.nuSMV.ModuleType#getPar <em>Par</em>}</li>
 * </ul>
 *
 * @see org.xtext.nusmv.language.nuSMV.NuSMVPackage#getModuleType()
 * @model
 * @generated
 */
public interface ModuleType extends Type
{
  /**
   * Returns the value of the '<em><b>Module</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Module</em>' reference.
   * @see #setModule(org.xtext.nusmv.language.nuSMV.Module)
   * @see org.xtext.nusmv.language.nuSMV.NuSMVPackage#getModuleType_Module()
   * @model
   * @generated
   */
  org.xtext.nusmv.language.nuSMV.Module getModule();

  /**
   * Sets the value of the '{@link org.xtext.nusmv.language.nuSMV.ModuleType#getModule <em>Module</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Module</em>' reference.
   * @see #getModule()
   * @generated
   */
  void setModule(org.xtext.nusmv.language.nuSMV.Module value);

  /**
   * Returns the value of the '<em><b>Params</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.nusmv.language.nuSMV.SimpleExpression}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Params</em>' containment reference list.
   * @see org.xtext.nusmv.language.nuSMV.NuSMVPackage#getModuleType_Params()
   * @model containment="true"
   * @generated
   */
  EList<SimpleExpression> getParams();

  /**
   * Returns the value of the '<em><b>Par</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Par</em>' reference.
   * @see #setPar(VarBody)
   * @see org.xtext.nusmv.language.nuSMV.NuSMVPackage#getModuleType_Par()
   * @model
   * @generated
   */
  VarBody getPar();

  /**
   * Sets the value of the '{@link org.xtext.nusmv.language.nuSMV.ModuleType#getPar <em>Par</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Par</em>' reference.
   * @see #getPar()
   * @generated
   */
  void setPar(VarBody value);

} // ModuleType
