/**
 * generated by Xtext 2.21.0
 */
package org.xtext.nusmv.language.nuSMV;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Nu Smv Model</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.nusmv.language.nuSMV.NuSmvModel#getModules <em>Modules</em>}</li>
 * </ul>
 *
 * @see org.xtext.nusmv.language.nuSMV.NuSMVPackage#getNuSmvModel()
 * @model
 * @generated
 */
public interface NuSmvModel extends EObject
{
  /**
   * Returns the value of the '<em><b>Modules</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.nusmv.language.nuSMV.Module}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Modules</em>' containment reference list.
   * @see org.xtext.nusmv.language.nuSMV.NuSMVPackage#getNuSmvModel_Modules()
   * @model containment="true"
   * @generated
   */
  EList<org.xtext.nusmv.language.nuSMV.Module> getModules();

} // NuSmvModel
