/**
 * generated by Xtext 2.21.0
 */
package org.xtext.nusmv.language.nuSMV;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Range Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.nusmv.language.nuSMV.RangeExpression#getLower <em>Lower</em>}</li>
 *   <li>{@link org.xtext.nusmv.language.nuSMV.RangeExpression#getUpper <em>Upper</em>}</li>
 * </ul>
 *
 * @see org.xtext.nusmv.language.nuSMV.NuSMVPackage#getRangeExpression()
 * @model
 * @generated
 */
public interface RangeExpression extends EObject
{
  /**
   * Returns the value of the '<em><b>Lower</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Lower</em>' attribute.
   * @see #setLower(String)
   * @see org.xtext.nusmv.language.nuSMV.NuSMVPackage#getRangeExpression_Lower()
   * @model
   * @generated
   */
  String getLower();

  /**
   * Sets the value of the '{@link org.xtext.nusmv.language.nuSMV.RangeExpression#getLower <em>Lower</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Lower</em>' attribute.
   * @see #getLower()
   * @generated
   */
  void setLower(String value);

  /**
   * Returns the value of the '<em><b>Upper</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Upper</em>' attribute.
   * @see #setUpper(String)
   * @see org.xtext.nusmv.language.nuSMV.NuSMVPackage#getRangeExpression_Upper()
   * @model
   * @generated
   */
  String getUpper();

  /**
   * Sets the value of the '{@link org.xtext.nusmv.language.nuSMV.RangeExpression#getUpper <em>Upper</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Upper</em>' attribute.
   * @see #getUpper()
   * @generated
   */
  void setUpper(String value);

} // RangeExpression
