/**
 * generated by Xtext 2.21.0
 */
package org.xtext.nusmv.language.nuSMV;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Set Element Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.nusmv.language.nuSMV.SetElementExpression#getVal <em>Val</em>}</li>
 * </ul>
 *
 * @see org.xtext.nusmv.language.nuSMV.NuSMVPackage#getSetElementExpression()
 * @model
 * @generated
 */
public interface SetElementExpression extends SimpleExpression
{
  /**
   * Returns the value of the '<em><b>Val</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Val</em>' reference.
   * @see #setVal(Val)
   * @see org.xtext.nusmv.language.nuSMV.NuSMVPackage#getSetElementExpression_Val()
   * @model
   * @generated
   */
  Val getVal();

  /**
   * Sets the value of the '{@link org.xtext.nusmv.language.nuSMV.SetElementExpression#getVal <em>Val</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Val</em>' reference.
   * @see #getVal()
   * @generated
   */
  void setVal(Val value);

} // SetElementExpression
