/**
 * generated by Xtext 2.21.0
 */
package org.xtext.nusmv.language.nuSMV;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Signed Word Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.nusmv.language.nuSMV.SignedWordType#getSignedNumber <em>Signed Number</em>}</li>
 * </ul>
 *
 * @see org.xtext.nusmv.language.nuSMV.NuSMVPackage#getSignedWordType()
 * @model
 * @generated
 */
public interface SignedWordType extends SimpleType
{
  /**
   * Returns the value of the '<em><b>Signed Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Signed Number</em>' attribute.
   * @see #setSignedNumber(String)
   * @see org.xtext.nusmv.language.nuSMV.NuSMVPackage#getSignedWordType_SignedNumber()
   * @model
   * @generated
   */
  String getSignedNumber();

  /**
   * Sets the value of the '{@link org.xtext.nusmv.language.nuSMV.SignedWordType#getSignedNumber <em>Signed Number</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Signed Number</em>' attribute.
   * @see #getSignedNumber()
   * @generated
   */
  void setSignedNumber(String value);

} // SignedWordType
