/**
 * generated by Xtext 2.21.0
 */
package org.xtext.nusmv.language.nuSMV;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Simple Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.nusmv.language.nuSMV.NuSMVPackage#getSimpleExpression()
 * @model
 * @generated
 */
public interface SimpleExpression extends EObject
{
} // SimpleExpression
