/**
 * generated by Xtext 2.21.0
 */
package org.xtext.nusmv.language.nuSMV;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Simple Type</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.xtext.nusmv.language.nuSMV.NuSMVPackage#getSimpleType()
 * @model
 * @generated
 */
public interface SimpleType extends Type
{
} // SimpleType
