/**
 * generated by Xtext 2.21.0
 */
package org.xtext.nusmv.language.nuSMV;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Single RTCTL Expression</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.nusmv.language.nuSMV.SingleRTCTLExpression#getCtlExpression <em>Ctl Expression</em>}</li>
 * </ul>
 *
 * @see org.xtext.nusmv.language.nuSMV.NuSMVPackage#getSingleRTCTLExpression()
 * @model
 * @generated
 */
public interface SingleRTCTLExpression extends RTCTLExpression
{
  /**
   * Returns the value of the '<em><b>Ctl Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Ctl Expression</em>' containment reference.
   * @see #setCtlExpression(EObject)
   * @see org.xtext.nusmv.language.nuSMV.NuSMVPackage#getSingleRTCTLExpression_CtlExpression()
   * @model containment="true"
   * @generated
   */
  EObject getCtlExpression();

  /**
   * Sets the value of the '{@link org.xtext.nusmv.language.nuSMV.SingleRTCTLExpression#getCtlExpression <em>Ctl Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Ctl Expression</em>' containment reference.
   * @see #getCtlExpression()
   * @generated
   */
  void setCtlExpression(EObject value);

} // SingleRTCTLExpression
