/**
 * generated by Xtext 2.21.0
 */
package org.xtext.nusmv.language.nuSMV;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>To Int</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.nusmv.language.nuSMV.ToInt#getArg <em>Arg</em>}</li>
 * </ul>
 *
 * @see org.xtext.nusmv.language.nuSMV.NuSMVPackage#getToInt()
 * @model
 * @generated
 */
public interface ToInt extends SimpleExpression
{
  /**
   * Returns the value of the '<em><b>Arg</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Arg</em>' containment reference.
   * @see #setArg(SimpleExpression)
   * @see org.xtext.nusmv.language.nuSMV.NuSMVPackage#getToInt_Arg()
   * @model containment="true"
   * @generated
   */
  SimpleExpression getArg();

  /**
   * Sets the value of the '{@link org.xtext.nusmv.language.nuSMV.ToInt#getArg <em>Arg</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Arg</em>' containment reference.
   * @see #getArg()
   * @generated
   */
  void setArg(SimpleExpression value);

} // ToInt
