/**
 * generated by Xtext 2.21.0
 */
package org.xtext.nusmv.language.nuSMV;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Trans Constraint</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.nusmv.language.nuSMV.TransConstraint#getTransExpression <em>Trans Expression</em>}</li>
 *   <li>{@link org.xtext.nusmv.language.nuSMV.TransConstraint#isSemicolon <em>Semicolon</em>}</li>
 * </ul>
 *
 * @see org.xtext.nusmv.language.nuSMV.NuSMVPackage#getTransConstraint()
 * @model
 * @generated
 */
public interface TransConstraint extends ModuleElement
{
  /**
   * Returns the value of the '<em><b>Trans Expression</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Trans Expression</em>' containment reference.
   * @see #setTransExpression(SimpleExpression)
   * @see org.xtext.nusmv.language.nuSMV.NuSMVPackage#getTransConstraint_TransExpression()
   * @model containment="true"
   * @generated
   */
  SimpleExpression getTransExpression();

  /**
   * Sets the value of the '{@link org.xtext.nusmv.language.nuSMV.TransConstraint#getTransExpression <em>Trans Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Trans Expression</em>' containment reference.
   * @see #getTransExpression()
   * @generated
   */
  void setTransExpression(SimpleExpression value);

  /**
   * Returns the value of the '<em><b>Semicolon</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Semicolon</em>' attribute.
   * @see #setSemicolon(boolean)
   * @see org.xtext.nusmv.language.nuSMV.NuSMVPackage#getTransConstraint_Semicolon()
   * @model
   * @generated
   */
  boolean isSemicolon();

  /**
   * Sets the value of the '{@link org.xtext.nusmv.language.nuSMV.TransConstraint#isSemicolon <em>Semicolon</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Semicolon</em>' attribute.
   * @see #isSemicolon()
   * @generated
   */
  void setSemicolon(boolean value);

} // TransConstraint
