/**
 * generated by Xtext 2.21.0
 */
package org.xtext.nusmv.language.nuSMV;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Unsigned Word Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.nusmv.language.nuSMV.UnsignedWordType#getUWordNumber <em>UWord Number</em>}</li>
 * </ul>
 *
 * @see org.xtext.nusmv.language.nuSMV.NuSMVPackage#getUnsignedWordType()
 * @model
 * @generated
 */
public interface UnsignedWordType extends SimpleType
{
  /**
   * Returns the value of the '<em><b>UWord Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>UWord Number</em>' attribute.
   * @see #setUWordNumber(String)
   * @see org.xtext.nusmv.language.nuSMV.NuSMVPackage#getUnsignedWordType_UWordNumber()
   * @model
   * @generated
   */
  String getUWordNumber();

  /**
   * Sets the value of the '{@link org.xtext.nusmv.language.nuSMV.UnsignedWordType#getUWordNumber <em>UWord Number</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>UWord Number</em>' attribute.
   * @see #getUWordNumber()
   * @generated
   */
  void setUWordNumber(String value);

} // UnsignedWordType
