/**
 * generated by Xtext 2.21.0
 */
package org.xtext.nusmv.language.nuSMV;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Var</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.nusmv.language.nuSMV.Var#getValue <em>Value</em>}</li>
 *   <li>{@link org.xtext.nusmv.language.nuSMV.Var#getDotted <em>Dotted</em>}</li>
 *   <li>{@link org.xtext.nusmv.language.nuSMV.Var#getArray <em>Array</em>}</li>
 * </ul>
 *
 * @see org.xtext.nusmv.language.nuSMV.NuSMVPackage#getVar()
 * @model
 * @generated
 */
public interface Var extends SimpleExpression
{
  /**
   * Returns the value of the '<em><b>Value</b></em>' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Value</em>' reference.
   * @see #setValue(VarBody)
   * @see org.xtext.nusmv.language.nuSMV.NuSMVPackage#getVar_Value()
   * @model
   * @generated
   */
  VarBody getValue();

  /**
   * Sets the value of the '{@link org.xtext.nusmv.language.nuSMV.Var#getValue <em>Value</em>}' reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Value</em>' reference.
   * @see #getValue()
   * @generated
   */
  void setValue(VarBody value);

  /**
   * Returns the value of the '<em><b>Dotted</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Dotted</em>' containment reference.
   * @see #setDotted(SimpleExpression)
   * @see org.xtext.nusmv.language.nuSMV.NuSMVPackage#getVar_Dotted()
   * @model containment="true"
   * @generated
   */
  SimpleExpression getDotted();

  /**
   * Sets the value of the '{@link org.xtext.nusmv.language.nuSMV.Var#getDotted <em>Dotted</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Dotted</em>' containment reference.
   * @see #getDotted()
   * @generated
   */
  void setDotted(SimpleExpression value);

  /**
   * Returns the value of the '<em><b>Array</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Array</em>' attribute list.
   * @see org.xtext.nusmv.language.nuSMV.NuSMVPackage#getVar_Array()
   * @model unique="false"
   * @generated
   */
  EList<String> getArray();

} // Var
