/**
 * generated by Xtext 2.21.0
 */
package org.xtext.nusmv.language.nuSMV;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Word Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.nusmv.language.nuSMV.WordType#getWordNumber <em>Word Number</em>}</li>
 * </ul>
 *
 * @see org.xtext.nusmv.language.nuSMV.NuSMVPackage#getWordType()
 * @model
 * @generated
 */
public interface WordType extends SimpleType
{
  /**
   * Returns the value of the '<em><b>Word Number</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Word Number</em>' attribute.
   * @see #setWordNumber(String)
   * @see org.xtext.nusmv.language.nuSMV.NuSMVPackage#getWordType_WordNumber()
   * @model
   * @generated
   */
  String getWordNumber();

  /**
   * Sets the value of the '{@link org.xtext.nusmv.language.nuSMV.WordType#getWordNumber <em>Word Number</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Word Number</em>' attribute.
   * @see #getWordNumber()
   * @generated
   */
  void setWordNumber(String value);

} // WordType
