/**
 * generated by Xtext 2.21.0
 */
package org.xtext.nusmv.language.nuSMV.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.nusmv.language.nuSMV.CTLExpression;
import org.xtext.nusmv.language.nuSMV.CtlSpecification;
import org.xtext.nusmv.language.nuSMV.NuSMVPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Ctl Specification</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.nusmv.language.nuSMV.impl.CtlSpecificationImpl#getSpecKeyWord <em>Spec Key Word</em>}</li>
 *   <li>{@link org.xtext.nusmv.language.nuSMV.impl.CtlSpecificationImpl#isNameKeyWord <em>Name Key Word</em>}</li>
 *   <li>{@link org.xtext.nusmv.language.nuSMV.impl.CtlSpecificationImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.nusmv.language.nuSMV.impl.CtlSpecificationImpl#getCtlExpression <em>Ctl Expression</em>}</li>
 *   <li>{@link org.xtext.nusmv.language.nuSMV.impl.CtlSpecificationImpl#isSemicolon <em>Semicolon</em>}</li>
 * </ul>
 *
 * @generated
 */
public class CtlSpecificationImpl extends ModuleElementImpl implements CtlSpecification
{
  /**
   * The default value of the '{@link #getSpecKeyWord() <em>Spec Key Word</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSpecKeyWord()
   * @generated
   * @ordered
   */
  protected static final String SPEC_KEY_WORD_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getSpecKeyWord() <em>Spec Key Word</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSpecKeyWord()
   * @generated
   * @ordered
   */
  protected String specKeyWord = SPEC_KEY_WORD_EDEFAULT;

  /**
   * The default value of the '{@link #isNameKeyWord() <em>Name Key Word</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isNameKeyWord()
   * @generated
   * @ordered
   */
  protected static final boolean NAME_KEY_WORD_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isNameKeyWord() <em>Name Key Word</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isNameKeyWord()
   * @generated
   * @ordered
   */
  protected boolean nameKeyWord = NAME_KEY_WORD_EDEFAULT;

  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The cached value of the '{@link #getCtlExpression() <em>Ctl Expression</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getCtlExpression()
   * @generated
   * @ordered
   */
  protected CTLExpression ctlExpression;

  /**
   * The default value of the '{@link #isSemicolon() <em>Semicolon</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isSemicolon()
   * @generated
   * @ordered
   */
  protected static final boolean SEMICOLON_EDEFAULT = false;

  /**
   * The cached value of the '{@link #isSemicolon() <em>Semicolon</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #isSemicolon()
   * @generated
   * @ordered
   */
  protected boolean semicolon = SEMICOLON_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected CtlSpecificationImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return NuSMVPackage.Literals.CTL_SPECIFICATION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getSpecKeyWord()
  {
    return specKeyWord;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSpecKeyWord(String newSpecKeyWord)
  {
    String oldSpecKeyWord = specKeyWord;
    specKeyWord = newSpecKeyWord;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, NuSMVPackage.CTL_SPECIFICATION__SPEC_KEY_WORD, oldSpecKeyWord, specKeyWord));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isNameKeyWord()
  {
    return nameKeyWord;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setNameKeyWord(boolean newNameKeyWord)
  {
    boolean oldNameKeyWord = nameKeyWord;
    nameKeyWord = newNameKeyWord;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, NuSMVPackage.CTL_SPECIFICATION__NAME_KEY_WORD, oldNameKeyWord, nameKeyWord));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, NuSMVPackage.CTL_SPECIFICATION__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public CTLExpression getCtlExpression()
  {
    return ctlExpression;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetCtlExpression(CTLExpression newCtlExpression, NotificationChain msgs)
  {
    CTLExpression oldCtlExpression = ctlExpression;
    ctlExpression = newCtlExpression;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, NuSMVPackage.CTL_SPECIFICATION__CTL_EXPRESSION, oldCtlExpression, newCtlExpression);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setCtlExpression(CTLExpression newCtlExpression)
  {
    if (newCtlExpression != ctlExpression)
    {
      NotificationChain msgs = null;
      if (ctlExpression != null)
        msgs = ((InternalEObject)ctlExpression).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - NuSMVPackage.CTL_SPECIFICATION__CTL_EXPRESSION, null, msgs);
      if (newCtlExpression != null)
        msgs = ((InternalEObject)newCtlExpression).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - NuSMVPackage.CTL_SPECIFICATION__CTL_EXPRESSION, null, msgs);
      msgs = basicSetCtlExpression(newCtlExpression, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, NuSMVPackage.CTL_SPECIFICATION__CTL_EXPRESSION, newCtlExpression, newCtlExpression));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean isSemicolon()
  {
    return semicolon;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setSemicolon(boolean newSemicolon)
  {
    boolean oldSemicolon = semicolon;
    semicolon = newSemicolon;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, NuSMVPackage.CTL_SPECIFICATION__SEMICOLON, oldSemicolon, semicolon));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case NuSMVPackage.CTL_SPECIFICATION__CTL_EXPRESSION:
        return basicSetCtlExpression(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case NuSMVPackage.CTL_SPECIFICATION__SPEC_KEY_WORD:
        return getSpecKeyWord();
      case NuSMVPackage.CTL_SPECIFICATION__NAME_KEY_WORD:
        return isNameKeyWord();
      case NuSMVPackage.CTL_SPECIFICATION__NAME:
        return getName();
      case NuSMVPackage.CTL_SPECIFICATION__CTL_EXPRESSION:
        return getCtlExpression();
      case NuSMVPackage.CTL_SPECIFICATION__SEMICOLON:
        return isSemicolon();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case NuSMVPackage.CTL_SPECIFICATION__SPEC_KEY_WORD:
        setSpecKeyWord((String)newValue);
        return;
      case NuSMVPackage.CTL_SPECIFICATION__NAME_KEY_WORD:
        setNameKeyWord((Boolean)newValue);
        return;
      case NuSMVPackage.CTL_SPECIFICATION__NAME:
        setName((String)newValue);
        return;
      case NuSMVPackage.CTL_SPECIFICATION__CTL_EXPRESSION:
        setCtlExpression((CTLExpression)newValue);
        return;
      case NuSMVPackage.CTL_SPECIFICATION__SEMICOLON:
        setSemicolon((Boolean)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case NuSMVPackage.CTL_SPECIFICATION__SPEC_KEY_WORD:
        setSpecKeyWord(SPEC_KEY_WORD_EDEFAULT);
        return;
      case NuSMVPackage.CTL_SPECIFICATION__NAME_KEY_WORD:
        setNameKeyWord(NAME_KEY_WORD_EDEFAULT);
        return;
      case NuSMVPackage.CTL_SPECIFICATION__NAME:
        setName(NAME_EDEFAULT);
        return;
      case NuSMVPackage.CTL_SPECIFICATION__CTL_EXPRESSION:
        setCtlExpression((CTLExpression)null);
        return;
      case NuSMVPackage.CTL_SPECIFICATION__SEMICOLON:
        setSemicolon(SEMICOLON_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case NuSMVPackage.CTL_SPECIFICATION__SPEC_KEY_WORD:
        return SPEC_KEY_WORD_EDEFAULT == null ? specKeyWord != null : !SPEC_KEY_WORD_EDEFAULT.equals(specKeyWord);
      case NuSMVPackage.CTL_SPECIFICATION__NAME_KEY_WORD:
        return nameKeyWord != NAME_KEY_WORD_EDEFAULT;
      case NuSMVPackage.CTL_SPECIFICATION__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case NuSMVPackage.CTL_SPECIFICATION__CTL_EXPRESSION:
        return ctlExpression != null;
      case NuSMVPackage.CTL_SPECIFICATION__SEMICOLON:
        return semicolon != SEMICOLON_EDEFAULT;
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (specKeyWord: ");
    result.append(specKeyWord);
    result.append(", nameKeyWord: ");
    result.append(nameKeyWord);
    result.append(", name: ");
    result.append(name);
    result.append(", semicolon: ");
    result.append(semicolon);
    result.append(')');
    return result.toString();
  }

} //CtlSpecificationImpl
