/**
 * generated by Xtext 2.21.0
 */
package org.xtext.nusmv.language.nuSMV.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.xtext.nusmv.language.nuSMV.JusticeExpression;
import org.xtext.nusmv.language.nuSMV.NuSMVPackage;
import org.xtext.nusmv.language.nuSMV.SimpleExpression;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Justice Expression</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.nusmv.language.nuSMV.impl.JusticeExpressionImpl#getJusticeExpr <em>Justice Expr</em>}</li>
 * </ul>
 *
 * @generated
 */
public class JusticeExpressionImpl extends FairnessConstraintImpl implements JusticeExpression
{
  /**
   * The cached value of the '{@link #getJusticeExpr() <em>Justice Expr</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getJusticeExpr()
   * @generated
   * @ordered
   */
  protected SimpleExpression justiceExpr;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected JusticeExpressionImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return NuSMVPackage.Literals.JUSTICE_EXPRESSION;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SimpleExpression getJusticeExpr()
  {
    return justiceExpr;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetJusticeExpr(SimpleExpression newJusticeExpr, NotificationChain msgs)
  {
    SimpleExpression oldJusticeExpr = justiceExpr;
    justiceExpr = newJusticeExpr;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, NuSMVPackage.JUSTICE_EXPRESSION__JUSTICE_EXPR, oldJusticeExpr, newJusticeExpr);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setJusticeExpr(SimpleExpression newJusticeExpr)
  {
    if (newJusticeExpr != justiceExpr)
    {
      NotificationChain msgs = null;
      if (justiceExpr != null)
        msgs = ((InternalEObject)justiceExpr).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - NuSMVPackage.JUSTICE_EXPRESSION__JUSTICE_EXPR, null, msgs);
      if (newJusticeExpr != null)
        msgs = ((InternalEObject)newJusticeExpr).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - NuSMVPackage.JUSTICE_EXPRESSION__JUSTICE_EXPR, null, msgs);
      msgs = basicSetJusticeExpr(newJusticeExpr, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, NuSMVPackage.JUSTICE_EXPRESSION__JUSTICE_EXPR, newJusticeExpr, newJusticeExpr));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case NuSMVPackage.JUSTICE_EXPRESSION__JUSTICE_EXPR:
        return basicSetJusticeExpr(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case NuSMVPackage.JUSTICE_EXPRESSION__JUSTICE_EXPR:
        return getJusticeExpr();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case NuSMVPackage.JUSTICE_EXPRESSION__JUSTICE_EXPR:
        setJusticeExpr((SimpleExpression)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case NuSMVPackage.JUSTICE_EXPRESSION__JUSTICE_EXPR:
        setJusticeExpr((SimpleExpression)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case NuSMVPackage.JUSTICE_EXPRESSION__JUSTICE_EXPR:
        return justiceExpr != null;
    }
    return super.eIsSet(featureID);
  }

} //JusticeExpressionImpl
