/**
 * generated by Xtext 2.21.0
 */
package org.xtext.nusmv.language.nuSMV.impl;

import org.eclipse.emf.ecore.EClass;

import org.xtext.nusmv.language.nuSMV.NuSMVPackage;
import org.xtext.nusmv.language.nuSMV.SyncrProcessType;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Syncr Process Type</b></em>'.
 * <!-- end-user-doc -->
 *
 * @generated
 */
public class SyncrProcessTypeImpl extends ModuleTypeImpl implements SyncrProcessType
{
  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected SyncrProcessTypeImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return NuSMVPackage.Literals.SYNCR_PROCESS_TYPE;
  }

} //SyncrProcessTypeImpl
